---
# vars file for spark
spark_release: "spark-2.2.0"
spark:
  download_url: "http://www-eu.apache.org/dist/spark/{{ spark_release }}/{{ spark_release }}-bin-hadoop2.7.tgz"
  install_dir: "/apps/spark"
  user: "spark"
  group: "spark"
  mode: "{{ spark_mode | default('master') }}"
  master:
    host: "{{ master_host | default('localhost') }}"
    port: "{{ master_port | default('7077') }}"
