---
# tasks file for spark

- block:

  - name: Create '{{ spark.group }}' user group
    group:
      name: "{{ spark.group }}"
      state: present

  - name: Create '{{ spark.user }}' user
    user:
      name: "{{ spark.user }}"
      group: "{{ spark.group }}"

  - name: Create spark installation directory
    file:
      path: "{{ spark.install_dir }}"
      state: directory

  - name: Download and extract spark
    unarchive:
      src: "{{ spark.download_url }}"
      dest: "{{ spark.install_dir }}"
      owner: "{{ spark.user }}"
      group: "{{ spark.group }}"
      remote_src: yes

  - name: Templatize '{{ spark.user }}' bash_profile
    template:
      src: "bash_profile.j2"
      dest: "/home/{{ spark.user }}/.bash_profile"
      owner: "{{ spark.user }}"
      group: "{{ spark.user }}"
      mode: '0600'

  - name: Templatize spark systemd service
    template:
      src: "spark-{{ spark.mode }}_systemd.j2"
      dest: "/etc/systemd/system/spark-{{ spark.mode }}.service"
      owner: "{{ spark.user }}"
      group: "{{ spark.user }}"
      mode: '0600'
    notify: restart spark-{{ spark.mode }}

  tags:
    - spark_install
